import './global.css';
import { ThemeProvider } from "@el-test/ui-components/components/theme-provider"

export const metadata = {
  title: 'Welcome to dashboard',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        {children}  
      </ThemeProvider>  
      </body>
    </html>
  );
}
